name: bakery_shop_admin_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  dio: ^5.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  connectivity_plus: ^4.0.2
  flutter_screenutil: ^5.9.0
  intl_phone_field: ^3.2.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  flutter_otp_text_field: ^1.1.1
  google_sign_in: ^6.1.5
  carousel_slider: ^4.2.1
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  hive: ^2.2.3
  app_tracking_transparency: ^2.0.3
  permission_handler: ^10.3.0
  android_id: ^0.0.7
  flutter_cache_manager: ^3.3.1
  flutter_isolate: ^2.0.4
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^15.1.0+1
  dart_ping: ^8.0.1
  dart_ping_ios: ^3.0.0
  # flutter_inappwebview: ^6.0.0-beta.25
  android_alarm_manager_plus: ^3.0.2
  crop_image: ^1.0.11
  extended_image: ^8.1.1
  pinput: ^3.0.1
  cached_network_image: ^3.3.0
  firebase_core: ^2.21.0
  firebase_analytics: ^10.0.5
  firebase_crashlytics: ^3.0.5
  firebase_messaging: 14.7.3
  device_info_plus: ^9.0.3
  http: ^1.1.0
  path_provider: ^2.1.1
  lottie: ^2.6.0
  flutter_sim_country_code: ^0.1.2
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  bloc: ^8.1.2
  flutter_native_contact_picker: ^0.0.4
  map_location_picker: ^1.2.8+3
  location_geocoder: ^1.0.5
  flutter_google_places_sdk: ^0.3.7
  firebase_auth: ^4.10.1
  flutter_html: ^3.0.0-beta.2
  in_app_review: ^2.0.8
  lazy_load_scrollview: ^1.3.0
  cloud_firestore: ^4.9.3
  image_editor: ^1.3.0
  video_player: ^2.8.1
  google_places_flutter:
    git:
      url: https://github.com/parthvirani-oceanmtech/Google-AutoComplete-TextField-Flutter.git
      ref: 56d55f84f2b81c90f11c5c35f13deb77e878f806
  appsflyer_sdk:
    git:
      url: https://github.com/parthvirani-oceanmtech/appsflyer-flutter-plugin.git
      ref: 6fff2e79d500aef07b1db95d709ef65b04cd3efc
  # date_picker_plus:
  #   git:
  #     url: https://github.com/avani-oceanmtech/date_picker.git
  #     ref: 33aa0b7119290094d94cfe75832d470db83a3de3
  catcher:
    git:
      url: https://github.com/parthvirani-oceanmtech/catcher.git
      ref: f434474
  calendar_date_picker2:
    git:
      url: https://github.com/oceanmtechanshraiyani/calendar_date_picker2
      ref: f8c15ef8352bd7e773a446eef6b12219db0fd45c
  universal_io: ^2.2.2
  hive_flutter: ^1.1.0
  localstorage: ^4.0.1+4
  responsive_grid_list: ^1.4.0
  image_picker_for_web: ^3.0.1
  dropdown_button2: ^2.3.9
  flutter_colorpicker: 
    git:
      url: https://github.com/OceanmtechHardik/flutter_colorpicker.git
      ref: b800576bf445a537ab491ca44ebace6444391be0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/fonts/
    - assets/photos/png/
    - assets/photos/png/home_page/
    - assets/photos/png/address_screen/
    - assets/photos/png/designed_boxes/
    - assets/photos/png/introduction_screen/
    - assets/photos/png/my_reward_points/
    - assets/photos/png/refer_earn_screen/
    - assets/photos/png/review_and_feedback_screen/
    - assets/photos/dummy/
    - assets/photos/svg/bottom_navigation_bar/
    - assets/photos/svg/drawer/
    - assets/photos/svg/appbar/
    - assets/photos/svg/common/
    - assets/photos/svg/edit_profile/
    - assets/photos/svg/setting_screen/
    - assets/photos/svg/once_used_picture/
    - assets/photos/svg/profile_screen/
    - assets/photos/svg/reward_coupon_screen/
    - assets/photos/svg/introduction_screen/
    - assets/photos/svg/setting_screen/address_screen/
    - assets/photos/svg/my_favorite_screen/
    - assets/photos/svg/product_screen/
    - assets/ca/
    - assets/photos/svg/offer_screen/
    - assets/photos/svg/offers_screen/
    - assets/photos/svg/refer_earn_screen/
    - assets/photos/svg/feedback/
    - assets/photos/svg/onboarding/
    - assets/photos/svg/tab_bar/
    - assets/photos/svg/address_screen/
    - assets/photos/svg/chat/
    - assets/photos/svg/order_status_screen/
    - assets/photos/svg/help_support/
    - assets/photos/svg/order_placed_screen/
    - assets/photos/svg/review_and_feedback_screen/
    - assets/photos/svg/cart_screen/
    - assets/photos/svg/google_map_scree/
    - assets/photos/svg/image_croper_screen/
    - assets/photos/svg/side_menu/
    - assets/photos/svg/dash_screen/
    - assets/photos/svg/customer/
    - assets/photos/svg/reminder_screen/
    - assets/photos/svg/catalog_screen/
    - assets/photos/svg/order_module/
    - assets/photos/svg/product_details/
    - assets/photos/svg/add_product/
    - assets/photos/svg/marketing_modul/
    - assets/photos/svg/settings_screen/
    - assets/photos/svg/expense_module_images/

  fonts:
    - family: Circular Std
      fonts:
        - asset: assets/fonts/CircularStd-Light.otf
          weight: 300
        - asset: assets/fonts/CircularStd-Book.otf
          weight: 400
        - asset: assets/fonts/CircularStd-Medium.otf
          weight: 500
        - asset: assets/fonts/CircularStd-Bold.otf
          weight: 700
        - asset: assets/fonts/CircularStd-Black.otf
          weight: 900

        - asset: assets/fonts/CircularStd-Light-Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/CircularStd-Book-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/CircularStd-Medium-Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/CircularStd-Bold-Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/CircularStd-Black-Italic.otf
          weight: 900
          style: italic
