// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrEpHAWLY0xJJ42vUwwxmLvbMEqyWGDkQ',
    appId: '1:965805024010:android:6b5416ef7304d128a790f3',
    messagingSenderId: '965805024010',
    projectId: 'bakery-shop-flutter',
    storageBucket: 'bakery-shop-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoK9tvlGuw-vpyVeK6AYue3vXbEji4kn8',
    appId: '1:965805024010:ios:9780d1d6b06245dfa790f3',
    messagingSenderId: '965805024010',
    projectId: 'bakery-shop-flutter',
    storageBucket: 'bakery-shop-flutter.appspot.com',
    androidClientId: '965805024010-aep3df9upg5m49dvjrn10dsb7r01epps.apps.googleusercontent.com',
    iosClientId: '965805024010-uep0qu9h75ojbooddc7p91ib2i3i8c2j.apps.googleusercontent.com',
    iosBundleId: 'com.oceanmtech.bakery.shop',
  );
}
