// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8sbok-jk4rIQVG6DhX3vrVad97__GqAY',
    appId: '1:1041606316442:web:9b0d062872dfe70279aa23',
    messagingSenderId: '1041606316442',
    projectId: 'bakery-shop-admin-flutter',
    authDomain: 'bakery-shop-admin-flutter.firebaseapp.com',
    storageBucket: 'bakery-shop-admin-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFTt4ZRZF1iT0GyeuvcfJUevL_KTWwnZE',
    appId: '1:1041606316442:android:9bef75f4eb7cbfef79aa23',
    messagingSenderId: '1041606316442',
    projectId: 'bakery-shop-admin-flutter',
    storageBucket: 'bakery-shop-admin-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-dQWB4cl8bEtljZ7xSX8Ymqq11MsHgfw',
    appId: '1:1041606316442:ios:d450d4cc8402addc79aa23',
    messagingSenderId: '1041606316442',
    projectId: 'bakery-shop-admin-flutter',
    storageBucket: 'bakery-shop-admin-flutter.appspot.com',
    iosBundleId: 'com.oceanmtech.bakery.shop.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-dQWB4cl8bEtljZ7xSX8Ymqq11MsHgfw',
    appId: '1:1041606316442:ios:bdcf53f10c69763879aa23',
    messagingSenderId: '1041606316442',
    projectId: 'bakery-shop-admin-flutter',
    storageBucket: 'bakery-shop-admin-flutter.appspot.com',
    iosBundleId: 'com.oceanmtech.bakery.shop.bakeryShopAdminFlutter.RunnerTests',
  );
}
