// ignore_for_file: prefer_final_fields, prefer_const_constructors

import 'package:flutter/material.dart';

//
class AppConstants {
  AppConstants() : super() {
    loadColor(true);
  }

  FontWeight appFontWeight = FontWeight.bold;
  FontWeight appFontW800 = FontWeight.w800;
  double iconSize = 32;
  double fontSize = 20;
  String intentDataChannel = "app.channel.shared.data";
  String intentDataChannelMethod = "getSharedText";
  IconThemeData appIconThemeData = IconThemeData(size: 26);

  int buttonRadius = 12;
  double prductCardRadius = 10;

  Color _black = Colors.black;
  Color _appTitle = Colors.black;
  Color _white = Colors.white;
  Color _iconColor = Colors.white;
  Color _notificationTextColor = Colors.white;
  //Color _drawerTextColor = Colors.white;
  Color _grey = Colors.grey;
  Color _black12 = Colors.black12;
  Color _black26 = Colors.black26;
  Color _black38 = Colors.black38;
  Color _black45 = Colors.black45;
  Color _black54 = Colors.black54;
  Color _black87 = Colors.black87;
  Color _red = Colors.red;
  Color _hintText = Colors.black38;
  Color _imagepickerbox = Color.fromRGBO(244, 244, 244, 1);
  Color _familyDetailsBox = Color.fromRGBO(245, 245, 245, 1);
  Color _starColor = Color.fromRGBO(255, 177, 59, 1);
  Color _backgroundColor = Color.fromRGBO(242, 242, 242, 1);
  Color _homeBackgroundColor = Color.fromRGBO(244, 244, 244, 1);
  Color _orenge = Color.fromRGBO(255, 231, 210, 1);
  Color _introScreenDescriptionText = Color.fromRGBO(34, 34, 34, 0.6);
  Color _disableButtonColor = Color.fromRGBO(34, 34, 34, 0.3);
  Color _familyDetailContainerTextColor = Color.fromRGBO(34, 34, 34, 0.4);
  Color _themeColor = Color.fromRGBO(8, 66, 119, 1);
  Color _containerColor = Color.fromRGBO(255, 244, 234, 1);
  Color _outOfRangeDotIndicator = Color.fromRGBO(229, 215, 202, 1);
  Color _coinColor = Color.fromRGBO(32, 63, 123, 1);
  Color _greyBorderColor = Colors.black87;
  Color _bestSellerContainer = Color.fromRGBO(255, 243, 225, 1);
  Color _paidColor = Color.fromRGBO(53, 121, 253, 1);
  Color _unpaidColor = Color.fromRGBO(240, 149, 13, 1);
  Color _editbuttonColor = Color.fromRGBO(67, 146, 241, 1);
  Color _deletebuttonColor = Color.fromRGBO(255, 63, 63, 1);
  Color _backGroundColor = Color.fromRGBO(237, 246, 255, 0.6);
  Color _referralCodeColor = Color.fromRGBO(0, 158, 44, 1);
  Color _viewContainerBackGroundColor = Color.fromRGBO(233, 243, 255, 1);
  Color _containerBoderColor = Color.fromRGBO(233, 243, 255, 1);
  Color _orderScreenSearchFieldBorderColor = Color.fromRGBO(211, 232, 255, 1);
  Color _orderScreenSelectedCategoryColor = Color.fromRGBO(67, 146, 241, 1);
  Color _quantityManageContainerColor = Color.fromRGBO(231, 240, 252, 1);
  Color _cookingWarning = Color.fromRGBO(8, 66, 119, 0.5);
  Color _green = Color.fromRGBO(0, 164, 16, 1);
  Color _shadowColor = Color.fromRGBO(218, 230, 242, 0.76);
  Color _borderColor = Color.fromRGBO(211, 232, 255, 1);
  Color _blueBgColor = Color.fromRGBO(221, 238, 255, 0.6);
  Color _deslectedBackGroundColor = Color.fromRGBO(232, 242, 255, 1);
  Color _textFiledColor = Color.fromRGBO(8, 66, 119, 0.4);

  Color _theme1Color = Color.fromRGBO(8, 66, 119, 1);
  Color _theme2Color = Color.fromRGBO(57, 104, 146, 1);
  Color _theme3Color = Color.fromRGBO(107, 142, 173, 1);
  Color _theme4Color = Color.fromRGBO(156, 179, 201, 1);
  Color _theme5Color = Color.fromRGBO(181, 198, 214, 1);
  Color _theme6Color = Color.fromRGBO(206, 217, 228, 1);
  Color _theme7Color = Color.fromRGBO(230, 236, 241, 1);
  Color _theme8Color = Color.fromRGBO(240, 244, 248, 1);

  Color _neutral1Color = Color.fromRGBO(41, 56, 71, 1);
  Color _neutral2Color = Color.fromRGBO(62, 76, 89, 1);
  Color _neutral3Color = Color.fromRGBO(84, 96, 108, 1);
  Color _neutral4Color = Color.fromRGBO(105, 116, 126, 1);
  Color _neutral5Color = Color.fromRGBO(127, 136, 145, 1);
  Color _neutral6Color = Color.fromRGBO(142, 163, 185, 1);
  Color _neutral7Color = Color.fromRGBO(148, 156, 163, 1);
  Color _neutral8Color = Color.fromRGBO(169, 175, 181, 1);
  Color _neutral9Color = Color.fromRGBO(191, 195, 200, 1);
  Color _neutral10Color = Color.fromRGBO(212, 215, 218, 1);
  Color _neutral11Color = Color.fromRGBO(234, 235, 237, 1);
  Color _neutral12Color = Color.fromRGBO(67, 146, 241, 0.5);
  Color _successAnimationColor = Color.fromRGBO(41, 56, 71, 1);
  Color _transparent = Colors.transparent;
  Color _drawerTextColor = Color.fromRGBO(156, 179, 201, 1);
  Color _drawerSplashColor = Color.fromRGBO(234, 245, 255, 1);
  Color _drawerBackgroundColor = Color.fromRGBO(255, 255, 255, 1);
  Color _dashlineColor = Color.fromRGBO(226, 234, 242, 1);
  Color _dividerColor = Color.fromRGBO(223, 223, 223, 1);
  Color _dateTextColor = Color.fromARGB(255, 19, 30, 41);
  Color _lightGrey = Color.fromRGBO(41, 56, 71, 0.4);
  Color _lightGrey1 = Color.fromRGBO(41, 56, 71, 0.7);
  Color _lightGrey2 = Color.fromRGBO(41, 56, 71, 0.1);
  Color _lightGrey3 = Color.fromRGBO(41, 56, 71, 0.3);
  Color _greyBorder = Color.fromRGBO(8, 66, 119, 0.4);
  Color _greyBorder1 = Color.fromRGBO(8, 66, 119, 0.8);
  Color _lightBlue = Color.fromRGBO(232, 242, 255, 1);
  Color _lightBlue1 = Color.fromRGBO(227, 233, 239, 1);
  Color _borderColor2 = Color.fromRGBO(8, 66, 119, 0.2);
  Color _containerBgColor = Color.fromRGBO(187, 218, 255, 1);
  Color _lightGrey4 = Color.fromRGBO(41, 56, 71, 0.6);
  Color _shadowColor1 = Color.fromRGBO(8, 66, 119, 0.08);
  Color _pendingColor = Color.fromRGBO(37, 184, 0, 1);
  Color _bottonColor = Color.fromRGBO(8, 66, 119, 1);
  Color _hotfavouritColor = Color.fromRGBO(220, 236, 255, 1);
  Color _dropdownColor = Color.fromRGBO(235, 242, 249, 1);
  Color _appliveColor = Color.fromRGBO(41, 56, 71, 0.6);
  Color _selfpointColor = Color.fromRGBO(240, 144, 0, 1);
  Color _barriarColor = Color.fromRGBO(41, 56, 71, 0.8);
  Color _datacolumColor = Color.fromRGBO(47, 101, 151, 1);
  Color _datacelColor = Color.fromRGBO(240, 240, 240, 1);
  Color _unselectborderColor = Color.fromRGBO(240, 240, 240, 1);
  Color _clearbuttonColor = Color.fromRGBO(220, 232, 243, 1);
  Color _pinColor = Color.fromRGBO(212, 212, 212, 1);
  Color _hintTextColor = Color.fromRGBO(142, 163, 185, 0.6);
  Color _titleBgColor = Color.fromRGBO(241, 248, 255, 1);
  Color _buttonBgColor = Color.fromRGBO(8, 66, 119, 0.16);
  Color _deleteBtnColor = Color.fromRGBO(255, 67, 67, 1);
  // Color _parrotColor = Color.fromRGBO(134, 209, 115, 1);
  Color _paymentTypeBgColor = Color.fromRGBO(232, 242, 255, 1);
  // Color _buttonColor = Color.fromRGBO(220, 232, 243, 1);
  Color _parrotColor = Color.fromRGBO(134, 209, 115, 1);
  Color _tableBorderColor = Color.fromRGBO(189, 203, 216, 1);

  late Color background;
  late Color appbarColor;
  late Color black;
  late Color iconColor;
  late Color appTitle;
  late Color drawerTextColor;
  late Color imagepickerbox;
  late Color introScreenDescriptionText;
  late Color paidColor;
  late Color coinColor;
  late Color unpaidColor;
  late Color refundOrderColor;
  late Color cancelledColor;
  late Color bestSellerContainer;
  late Color deliveredColor;
  late Color white;
  late Color orenge;
  late Color familyDetailsBox;
  late Color starColor;
  late Color disableButtonColor;
  late Color familyDetailContainerTextColor;
  late Color notificationTextColor;
  late Color containerColor;
  late Color backgroundColor;
  late Color homeBackgroundColor;
  late Color outOfRangeDotIndicator;
  late Color black12; // grey0
  late Color black26; // grey1
  late Color black38; // grey2
  late Color black45; // grey3
  late Color black54; // grey4
  late Color black87; // grey5
  late Color grey;
  late Color textColor;
  late Color red;
  late Color hintText;
  late Color themeColor;
  late Color greyBorderColor;
  late Color offerAndCoponsColor;
  late Color deactiveContainerColor;
  late Color cartBillDetailsTextColor;
  late Color timeSlotSelectedColor;
  late Color diselectAddbuttonColor;
  late Color successAnimationColor;
  late Color editbuttonColor;
  late Color deletebuttonColor;
  late Color backGroundColor;
  late Color referralCodeColor;
  late Color viewContainerBackGroundColor;
  late Color containerBoderColor;
  late Color orderScreenSearchFieldBorderColor;
  late Color orderScreenSelectedCategoryColor;
  late Color quantityManageContainerColor;
  late Color cookingWarning;
  late Color green;
  late Color shadowColor;
  late Color borderColor;
  late Color deslectedBackGroundColor;
  late Color textFiledColor;
  late Color lightBlue;
  late Color lightBlue1;
  late Color borderColor2;

  late Color theme1Color;
  late Color theme2Color;
  late Color theme3Color;
  late Color theme4Color;
  late Color theme5Color;
  late Color theme6Color;
  late Color theme7Color;
  late Color theme8Color;
  late Color neutral1Color;
  late Color neutral2Color;
  late Color neutral3Color;
  late Color neutral4Color;
  late Color neutral5Color;
  late Color neutral6Color;
  late Color neutral7Color;
  late Color neutral8Color;
  late Color neutral9Color;
  late Color neutral10Color;
  late Color neutral11Color;
  late Color neutral12Color;
  late Color transparent;
  late Color icon;

  late Color drawerSplashColor;
  late Color drawerBackgroundColor;
  late Color dashlineColor;
  late Color dividerColor;
  late Color dateTextColor;
  late Color blueBgColor;
  late Color lightGrey;
  late Color greyBorder;
  late Color greyBorder1;
  late Color lightGrey1;
  late Color lightGrey2;
  late Color lightGrey3;
  late Color containerBgColor;
  late Color lightGrey4;
  late Color shadowColor1;
  late Color pendingColor;
  late Color buttonColor;
  late Color hotfavouritColor;
  late Color dropdownColor;
  late Color appliveColor;
  late Color selfpointColor;
  late Color barriarColor;
  late Color datacolumColor;
  late Color datacelColor;
  late Color unselectborderColor;
  late Color clearbuttonColor;
  late Color pinColor;
  late Color hintTextColor;
  late Color titleBgColor;
  late Color buttonBgColor;
  late Color deleteBtnColor;
  late Color paymentTypeBgColor;
  late Color parrotColor;
  late Color tableBorderColor;

  void loadColor(bool isLightMode) {
    if (isLightMode) {
      loadLight();
    } else {
      loadDark();
    }
  }

  void loadLight() {
    theme1Color = _theme1Color;
    theme2Color = _theme2Color;
    theme3Color = _theme3Color;
    theme4Color = _theme4Color;
    theme5Color = _theme5Color;
    theme6Color = _theme6Color;
    theme7Color = _theme7Color;
    theme8Color = _theme8Color;
    offerAndCoponsColor = _theme1Color;
    neutral1Color = _neutral1Color;
    neutral2Color = _neutral2Color;
    neutral3Color = _neutral3Color;
    neutral4Color = _neutral4Color;
    neutral5Color = _neutral5Color;
    neutral6Color = _neutral6Color;
    neutral7Color = _neutral7Color;
    neutral8Color = _neutral8Color;
    neutral9Color = _neutral9Color;
    neutral10Color = _neutral10Color;
    neutral11Color = _neutral11Color;
    drawerSplashColor = _drawerSplashColor;
    drawerBackgroundColor = _drawerBackgroundColor;
    dashlineColor = _dashlineColor;
    deslectedBackGroundColor = _deslectedBackGroundColor;
    textFiledColor = _textFiledColor;

    themeColor = _theme1Color;
    background = _white;
    appbarColor = _white;
    iconColor = _iconColor;
    black = _black;
    drawerTextColor = _drawerTextColor;
    orenge = _orenge;
    starColor = _starColor;
    coinColor = _coinColor;
    white = _white;
    paidColor = _paidColor;
    unpaidColor = _unpaidColor;
    bestSellerContainer = _bestSellerContainer;
    imagepickerbox = _imagepickerbox;
    disableButtonColor = _disableButtonColor;
    familyDetailsBox = _familyDetailsBox;
    familyDetailContainerTextColor = _familyDetailContainerTextColor;
    appTitle = _appTitle;
    backgroundColor = _backgroundColor;
    outOfRangeDotIndicator = _outOfRangeDotIndicator;
    homeBackgroundColor = _homeBackgroundColor;
    notificationTextColor = _notificationTextColor;
    containerColor = _containerColor;
    textColor = _black;
    introScreenDescriptionText = _introScreenDescriptionText;
    grey = _grey;
    black12 = _black12;
    black26 = _black26;
    black38 = _black38;
    black45 = _black45;
    black54 = _black54;
    black87 = _black87;
    red = _red;
    hintText = _hintText;
    greyBorderColor = _greyBorderColor;
    successAnimationColor = _successAnimationColor;
    transparent = _transparent;
    icon = _black;
    timeSlotSelectedColor = _theme1Color;
    editbuttonColor = _editbuttonColor;
    deletebuttonColor = _deletebuttonColor;
    backGroundColor = _backGroundColor;
    referralCodeColor = _referralCodeColor;
    viewContainerBackGroundColor = _viewContainerBackGroundColor;
    containerBoderColor = _containerBoderColor;
    orderScreenSearchFieldBorderColor = _orderScreenSearchFieldBorderColor;
    orderScreenSelectedCategoryColor = _orderScreenSelectedCategoryColor;
    quantityManageContainerColor = _quantityManageContainerColor;
    cookingWarning = _cookingWarning;
    green = _green;
    shadowColor = _shadowColor;
    borderColor = _borderColor;
    dividerColor = _dividerColor;
    dateTextColor = _dateTextColor;
    blueBgColor = _blueBgColor;
    lightGrey = _lightGrey;
    greyBorder = _greyBorder;
    greyBorder1 = _greyBorder1;
    lightBlue = _lightBlue;
    lightGrey1 = _lightGrey1;
    lightGrey2 = _lightGrey2;
    lightGrey3 = _lightGrey3;
    lightGrey4 = _lightGrey4;
    lightBlue1 = _lightBlue1;
    borderColor2 = _borderColor2;
    containerBgColor = _containerBgColor;
    shadowColor1 = _shadowColor1;
    pendingColor = _pendingColor;
    buttonColor = _bottonColor;
    hotfavouritColor = _hotfavouritColor;
    dropdownColor = _dropdownColor;
    appliveColor = _appliveColor;
    selfpointColor = _selfpointColor;
    barriarColor = _barriarColor;
    datacolumColor = _datacolumColor;
    datacelColor = _datacelColor;
    unselectborderColor = _unselectborderColor;
    clearbuttonColor = _clearbuttonColor;
    pinColor = _pinColor;
    hintTextColor = _hintTextColor;
    titleBgColor = _titleBgColor;
    buttonBgColor = _buttonBgColor;
    deleteBtnColor = _deleteBtnColor;
    neutral12Color = _neutral12Color;
    paymentTypeBgColor = _paymentTypeBgColor;
    neutral12Color = _neutral12Color;
    shadowColor1 = _shadowColor1;
    parrotColor = _parrotColor;
    tableBorderColor = _tableBorderColor;
  }

  void loadDark() {
    theme1Color = _theme1Color;
    theme2Color = _theme2Color;
    theme3Color = _theme3Color;
    theme4Color = _theme4Color;
    theme5Color = _theme5Color;
    theme6Color = _theme6Color;
    theme7Color = _theme7Color;
    theme8Color = _theme8Color;
    neutral1Color = _neutral1Color;
    neutral2Color = _neutral2Color;
    neutral3Color = _neutral3Color;
    neutral4Color = _neutral4Color;
    neutral5Color = _neutral5Color;
    neutral6Color = _neutral6Color;
    neutral7Color = _neutral7Color;
    neutral8Color = _neutral8Color;
    neutral9Color = _neutral9Color;
    neutral10Color = _neutral10Color;
    neutral11Color = _neutral11Color;
    themeColor = _themeColor;
    background = _black;
    appbarColor = _white;
    iconColor = _iconColor;
    starColor = _starColor;
    introScreenDescriptionText = _introScreenDescriptionText;
    notificationTextColor = _notificationTextColor;
    orenge = _orenge;
    drawerTextColor = _drawerTextColor;
    coinColor = _coinColor;
    black = _white;
    appTitle = _appTitle;
    disableButtonColor = _disableButtonColor;
    backgroundColor = _backgroundColor;
    homeBackgroundColor = _homeBackgroundColor;
    familyDetailsBox = _familyDetailsBox;
    familyDetailContainerTextColor = _familyDetailContainerTextColor;
    textColor = _white;
    bestSellerContainer = _bestSellerContainer;
    paidColor = _paidColor;
    unpaidColor = _unpaidColor;
    outOfRangeDotIndicator = _outOfRangeDotIndicator;
    containerColor = _containerColor;
    grey = _grey;
    imagepickerbox = _imagepickerbox;
    black12 = _black12;
    black26 = _black26;
    black38 = _black38;
    black45 = _black45;
    black54 = _black54;
    black87 = _black87;
    red = _red;
    hintText = _white;
    greyBorderColor = _greyBorderColor;
    successAnimationColor = _successAnimationColor;
    transparent = _transparent;
    icon = _black;
    offerAndCoponsColor = _theme1Color;
    timeSlotSelectedColor = _theme1Color;
    editbuttonColor = _editbuttonColor;
    deletebuttonColor = _deletebuttonColor;
    backGroundColor = _backGroundColor;
    referralCodeColor = _referralCodeColor;
    viewContainerBackGroundColor = _viewContainerBackGroundColor;
    containerBoderColor = _containerBoderColor;
    orderScreenSearchFieldBorderColor = _orderScreenSearchFieldBorderColor;
    orderScreenSelectedCategoryColor = _orderScreenSelectedCategoryColor;
    quantityManageContainerColor = _quantityManageContainerColor;
    cookingWarning = _cookingWarning;
    green = _green;
    shadowColor = _shadowColor;
    borderColor = _borderColor;
    dividerColor = _dividerColor;
    dateTextColor = _dateTextColor;
    blueBgColor = _blueBgColor;
    deslectedBackGroundColor = _deslectedBackGroundColor;
    textFiledColor = _textFiledColor;
    lightGrey = _lightGrey;
    greyBorder = _greyBorder;
    greyBorder1 = _greyBorder1;
    lightBlue = _lightBlue;
    lightGrey1 = _lightGrey1;
    lightGrey2 = _lightGrey2;
    lightGrey3 = _lightGrey3;
    lightGrey4 = _lightGrey4;
    lightBlue1 = _lightBlue1;
    borderColor2 = _borderColor2;
    containerBgColor = _containerBgColor;
    shadowColor1 = _shadowColor1;
    pendingColor = _pendingColor;
    buttonColor = _bottonColor;
    hotfavouritColor = _hotfavouritColor;
    dropdownColor = _dropdownColor;
    appliveColor = _appliveColor;
    selfpointColor = _selfpointColor;
    barriarColor = _barriarColor;
    datacolumColor = _datacolumColor;
    datacelColor = _datacelColor;
    unselectborderColor = _unselectborderColor;
    clearbuttonColor = _clearbuttonColor;
    pinColor = _pinColor;
    hintTextColor = _hintTextColor;
    titleBgColor = _titleBgColor;
    buttonBgColor = _buttonBgColor;
    deleteBtnColor = _deleteBtnColor;
    neutral12Color = _neutral12Color;
    paymentTypeBgColor = _paymentTypeBgColor;
    neutral12Color = _neutral12Color;
    shadowColor1 = _shadowColor1;
    parrotColor = _parrotColor;
    tableBorderColor = _tableBorderColor;
  }
}
